"""empty message

Revision ID: 57884243f501
Revises: d3b4a26af6ed
Create Date: 2021-02-20 11:48:43.627285

"""

# revision identifiers, used by Alembic.
revision = '57884243f501'
down_revision = 'd3b4a26af6ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('publish_right', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'publish_right')
    # ### end Alembic commands ###
