"""empty message

Revision ID: 75819def1a6c
Revises: 57884243f501
Create Date: 2021-02-20 21:02:14.902880

"""

# revision identifiers, used by Alembic.
revision = '75819def1a6c'
down_revision = '57884243f501'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
